services:
  frontend:
    build:
      context: ./.devcontainer
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
      - backend_venv:/workspace/backend/.venv
    working_dir: /workspace
    command: bash ./scripts/dev.sh
    ports:
      - "5173:5173"
      - "8000:8000"
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/workspace/backend:rw
      - backend_venv:/workspace/backend/.venv

    working_dir: /workspace/backend
    # ports:
    #   - "8000:8000"

volumes:
  backend_venv:
